export const LAST_UPDATED = "2026-06-23 15:00 IDT";

export const WORKTREES = [
  {
    ticket: "JN-5724",
    ticketUrl: "https://jounce.atlassian.net/browse/JN-5724",
    title: "Reduce Lychee precommit flaky results",
    branch: "jn-5724-lychee-precommit-flaky",
    worktreePath: "/Users/josephberry/.agor/worktrees/Jounce-IO/jounce/jn-5724-lychee-precommit-flaky",
    zone: "Publish",
    pr: "#1622 DRAFT",
    prUrl: "https://github.com/Jounce-IO/jounce/pull/1622",
    status: "🟢 PR #1622 CREATED — DRAFT, MERGEABLE, all CI PASS (run 28020178138). Jira In Review. Needs promotion from DRAFT.",
    blockedOn: "Awaiting DRAFT promotion",
    blockedType: "running",
    sessionUrl: "http://localhost:3030/ui/s/019ef3e3ea0e734d882e878e/",
    sessionLabel: "publish session (complete)",
    lastActive: "2026-06-23 10:28 IDT",
  },
  {
    ticket: "JN-5616",
    ticketUrl: "https://jounce.atlassian.net/browse/JN-5616",
    title: "Replace find_project_root() calls in tests with conftest fixture",
    branch: "jn-5616-replace-find-project-root",
    worktreePath: "/Users/josephberry/.agor/worktrees/Jounce-IO/jounce/jn-5616-replace-find-project-root",
    zone: "Publish",
    pr: "#1623 DRAFT",
    prUrl: "https://github.com/Jounce-IO/jounce/pull/1623",
    status: "🟢 PR #1623 CREATED — DRAFT, MERGEABLE, all CI PASS (run 28020219339). Jira In Review. Needs promotion from DRAFT.",
    blockedOn: "Awaiting DRAFT promotion",
    blockedType: "running",
    sessionUrl: "http://localhost:3030/ui/s/019ef405c3e3746c900eac40/",
    sessionLabel: "publish session (complete)",
    lastActive: "2026-06-23 10:33 IDT",
  },
  {
    ticket: "JN-5677",
    sprint: "current",
    ticketUrl: "https://jounce.atlassian.net/browse/JN-5677",
    title: "Historical mode notebook cells",
    branch: "jn-5677-dev-historical-mode-notebook-cells",
    worktreePath: "/Users/josephberry/.agor/worktrees/Jounce-IO/jounce/jn-5677-dev-historical-mode-notebook-cells",
    zone: "Revise",
    pr: "#1615 DRAFT",
    prUrl: "https://github.com/Jounce-IO/jounce/pull/1615",
    status: "🔴 DRAFT + CONFLICTING + pre-commit FAIL — UNBLOCK: resolve conflicts, fix pre-commit, promote from DRAFT. Jira Done.",
    blockedOn: "Merge conflict + DRAFT + pre-commit FAIL",
    blockedType: "blocked",
    sessionUrl: "http://localhost:3030/ui/s/019eeaf04583757a89f47a99/",
    sessionLabel: "revise session",
    lastActive: "2026-06-22 14:25 IDT (squash message composed)",
  },
  {
    ticket: "JN-5546",
    ticketUrl: "https://jounce.atlassian.net/browse/JN-5546",
    title: "Document module layout convention",
    branch: "jn-5546-docs",
    worktreePath: "/Users/josephberry/.agor/worktrees/Jounce-IO/jounce/jn-5546-docs-document-module-layout-convention-and-3",
    zone: "Code Review",
    pr: "#1588",
    prUrl: "https://github.com/Jounce-IO/jounce/pull/1588",
    status: "🔴 pre-commit FAIL (run 27933817996). PR is MERGEABLE (no conflicts). Fix pre-commit, then assign reviewer. Jira should be 'In Review'.",
    blockedOn: "pre-commit FAIL (CI run 27933817996)",
    blockedType: "blocked",
    sessionUrl: "http://localhost:3030/ui/s/019ed01e5624752fbade0eab/",
    sessionLabel: "fix session",
    lastActive: "2026-06-17 10:14 IDT",
  },
  {
    ticket: null,
    ticketUrl: null,
    title: "Internal code review system",
    branch: "internal-cr-system",
    worktreePath: "/Users/josephberry/.agor/worktrees/Jounce-IO/jounce/internal-cr-system",
    zone: "Code",
    pr: null,
    prUrl: null,
    status: "⚠️ Session idle since 09:50 IDT after re-dispatch. Status unclear — check session for results.",
    blockedOn: "status unclear after re-dispatch",
    blockedType: "running",
    sessionUrl: "http://localhost:3030/ui/s/019eda0ae5667f0fa8bf3d95/",
    sessionLabel: "Phase 2 session",
    lastActive: "2026-06-23 09:50 IDT (agents re-dispatched)",
  },
  {
    ticket: "JN-5695",
    ticketUrl: "https://jounce.atlassian.net/browse/JN-5695",
    title: "DB connect script",
    branch: "jn-5695-db-connect-script",
    worktreePath: "/Users/josephberry/.agor/worktrees/Jounce-IO/jounce/jn-5695-db-connect-script",
    zone: "BLOCKED",
    pr: "#1596 DRAFT",
    prUrl: "https://github.com/Jounce-IO/jounce/pull/1596",
    status: "Frozen — solved locally with Docker DB; PR CONFLICTING",
    blockedOn: "Frozen",
    blockedType: "blocked",
    sessionUrl: null,
    sessionLabel: null,
    lastActive: "2026-06-15 17:23 IDT",
  },
  {
    ticket: "JN-5672",
    ticketUrl: "https://jounce.atlassian.net/browse/JN-5672",
    title: "DAL extensions for dashboard queries",
    branch: "jn-5672-dal-ext-dashboard",
    worktreePath: "/Users/josephberry/.agor/worktrees/Jounce-IO/jounce/jn-5672-dal-ext-dashboard",
    zone: "BLOCKED",
    pr: null,
    prUrl: null,
    status: "On hold — after notebooks complete",
    blockedOn: "On hold",
    blockedType: "blocked",
    sessionUrl: null,
    sessionLabel: null,
    lastActive: "2026-06-14 15:00 IDT",
  },
];

export const MERGED = [
  {
    ticket: "JN-5759",
    ticketUrl: null,
    title: "fix(validator): add missing detail field to responses multimodal test",
    pr: "#1619",
    prUrl: "https://github.com/Jounce-IO/jounce/pull/1619",
    mergedDate: "2026-06-23",
    note: "Merged 12:30 IDT Jun 23 — off-board PR; caused #1606 to re-conflict",
  },
  {
    ticket: "JN-5676",
    ticketUrl: "https://jounce.atlassian.net/browse/JN-5676",
    title: "Notebook scaffold + operational mode",
    pr: "#1604",
    prUrl: "https://github.com/Jounce-IO/jounce/pull/1604",
    mergedDate: "2026-06-23",
    note: "Merged 10:51 IDT Jun 23 — worktree archived 11:30 IDT heartbeat",
  },
  {
    ticket: "JN-5685/JN-5679",
    ticketUrl: "https://jounce.atlassian.net/browse/JN-5685",
    title: "Monotonicity verdict persistence tables and ingestion",
    pr: "#1602",
    prUrl: "https://github.com/Jounce-IO/jounce/pull/1602",
    mergedDate: "2026-06-22",
    note: "Merged 14:34 IDT Jun 22 — off-board PR by Uri Shaket",
  },
  {
    ticket: "JN-5675",
    ticketUrl: "https://jounce.atlassian.net/browse/JN-5675",
    title: "Historical visibility functions",
    pr: "#1601",
    prUrl: "https://github.com/Jounce-IO/jounce/pull/1601",
    mergedDate: "2026-06-21",
    note: "Merged 16:15 IDT Jun 21 — worktree archived 14:30 IDT",
  },
  {
    ticket: "JN-5730",
    ticketUrl: "https://jounce.atlassian.net/browse/JN-5730",
    title: "Auto apply jbenchmark and argocd labels",
    pr: "#1605",
    prUrl: "https://github.com/Jounce-IO/jounce/pull/1605",
    mergedDate: "2026-06-21",
    note: "Merged 10:50 IDT Jun 21 by ushaket — off-board PR",
  },
  {
    ticket: "JN-5729",
    ticketUrl: "https://jounce.atlassian.net/browse/JN-5729",
    title: "Hotfix: pin uv default Python to 3.13",
    pr: "#1608",
    prUrl: "https://github.com/Jounce-IO/jounce/pull/1608",
    mergedDate: "2026-06-21",
    note: "Merged 09:37 IDT Jun 21 — worktrees archived 12:00 IDT",
  },
  {
    ticket: "JN-5674",
    ticketUrl: "https://jounce.atlassian.net/browse/JN-5674",
    title: "Operational visibility functions",
    pr: "#1599",
    prUrl: "https://github.com/Jounce-IO/jounce/pull/1599",
    mergedDate: "2026-06-18",
    note: "Merged 23:55 IDT Jun 18 — Jira Done confirmed Jun 23",
  },
  {
    ticket: "JN-5673",
    ticketUrl: "https://jounce.atlassian.net/browse/JN-5673",
    title: "Visibility module scaffold",
    pr: "#1595",
    prUrl: "https://github.com/Jounce-IO/jounce/pull/1595",
    mergedDate: "2026-06-17",
    note: "Jira Done confirmed Jun 23 (was stale In Review for 6 days)",
  },
];

export const ALERTS = [
  {
    level: "green",
    message: "🟢 PR #1622 (JN-5724, Publish): DRAFT created — MERGEABLE, all CI PASS. Promote from DRAFT when ready.",
  },
  {
    level: "green",
    message: "🟢 PR #1623 (JN-5616, Publish): DRAFT created — MERGEABLE, all CI PASS. Promote from DRAFT when ready.",
  },
  {
    level: "red",
    message: "🔴 PR #1606 (JN-5725, off-board): CI FAILED — run 28015066339 e2e-smoke + e2e-tests FAILED. PR also CONFLICTING. Needs: (1) fix e2e failures, (2) rebase onto main, (3) new CI run. JN-5725 Done.",
  },
  {
    level: "red",
    message: "🔴 PR #1615 (JN-5677, Revise zone): DRAFT + CONFLICTING + pre-commit FAIL — UNBLOCK: resolve conflicts, fix pre-commit, promote from DRAFT. Jira already Done.",
  },
  {
    level: "red",
    message: "🔴 PR #1588 (JN-5546, Code Review zone): pre-commit FAIL — CI run 27933817996. PR is MERGEABLE (no git conflicts). Fix pre-commit, assign reviewer, update Jira to 'In Review'.",
  },
  {
    level: "yellow",
    message: "⚠️ internal-cr-system (Code zone): session idle since 09:50 IDT after re-dispatch. Check session 019eda0a for results.",
  },
];
